spring:
  application:
    name: admin-server
    include: common,eureka,db,redis,rabbitmq
mybatis:
  type-aliases-package: top.liuyanhua.admin.server.models
  mapper-locations: classpath:mapper/*.xml